package pl.mikulski.songbook;

public class Sample {
	
	public static final String[] TEST_ARRAY = new String[] { "1788",
			"A my nie chcemy uciekaÊ stπd", "A ty walcz", "Abordaø",
			"Ach, kiedy znowu ruszπ dla mnie dni", "Aleksander Siergiejewicz Puszkin",
			"Aleksander Wat", "Alleluja", "Arka Noego", "Autoportret Witkacego", "Ave Virgo Maria",
			"Bagno", "Bajeczki Babci Pimpusiowej", "Bajka", "Bajka o G≥upim Jasiu",
			"Bal kreúlarzy", "Ballada majowa", "Ballada o starym wilku",
			"Ballada o trzeüwym diable", "Ballada o úw. Miko≥aju", "Ballada pozytywna", "Banita",
			"Bar w Beskidzie", "Ba≥tyckie Morze", "Bieszczady", "Bieszczadzkie anio≥y", "Bitwa",
			"Blues dla Ma≥ej", "BÛj", "BÍdziesz mojπ paniπ", "Ch≥opcy z Botany Bay", "Czarna rafa",
			"Czarnobrody kapitan", "Czarny blues o czwartej nad ranem", "Diana",
			"Dlaczego Pan Tadeusz?", "Do Marka Aurelego", "Dobre rady Pana Ojca",
			"Drzewo genealogiczne", "DziewiÍÊdziesiÍciu siedmiu konfederatÛw w Pakoúci",
			"DzieÒ úw. Patryka", "Emeryt", "Epitafium dla W≥odzimierza Wysockiego",
			"Francois Villon", "Gdy kina WolnoúÊ", "Gwiazda z powiatu Down", "GÛr mi ma≥o",
			"Hawaje", "Heave away Santiano", "Hej ruszajmy",
			"Historia z≥ego sternika, co nie uøywa≥ grzebyka", "HiszpaÒskie dziewczyny",
			"Houyhnhnm", "Hymn wieczoru kawalerskiego, czyli øale polonistycznych degeneratÛw",
			"Jan Kochanowski", "Jasnow≥osa", "Ja≥ta", "Jesienne wino", "JesieÒ idzie",
			"Jesztio raz", "Kantyczka z lotu ptaka", "Kapitan Nash", "Kara Barabasza",
			"Karmaniola", "Kibel II", "Kim w≥aúciwie by≥a ta piÍkna pani", "Knajpa mordercÛw",
			"Kochaj mnie i dotykaj", "Komu dzwoniπ, temu dzwoniπ", "Korsarze", "Kozioroøec",
			"Ko≥ysanka dla misiakÛw", "Ko≥ysanka pijacka", "Krajobraz po uczcie",
			"Lalka, czyli polski pozytywizm", "Laputa", "Lauren Grey",
			"Lekcja historii klasycznej", "List do Ogrodowej", "Machiavelli", "Maki",
			"Malcziszka z Leningrada", "Malowani", "Malowani", "Marco Polo",
			"Margrabia Wielopolski", "Marksobianka", "Miejcie nadziejÍ", "Mi≥a", "Modlitwa",
			"Modlitwa o wschodzie s≥oÒca", "Modlitwa wÍdrownego grajka", "Morza psy", "Mufka",
			"Murka", "Mury", "MÍczennicy sandomierscy", "Narodziny úwiata", "Nasza klasa",
			"Nasze przebudzenie", "Nie brookliÒski most", "Noc albo oczekiwanie na úniadanie",
			"O jednej Wiúniewskiej", "O tej muzyce ñ piosenka z cytatem",
			"O zachowaniu przy stole", "Ocean", "Odezwij siÍ", "Odynie", "Okruszyna",
			"OpowieúÊ pewnego emigranta", "Pan Kmicic", "Pan Wo≥odyjowski", "Pawlak",
			"Pejzaøe harasymowiczowskie", "PieúÒ Dawida na pustyni", "PieúÒ nad pieúniami",
			"PieúÒ o Gofredzie z Bulionu", "Piosenka dla Wojtka Bellona", "Piosenka z szabli",
			"Po ciemku", "Poczekalnia", "Pod kπtem ostrym", "Polanka", "Polish Wunderwaffe",
			"Port", "Port Royale", "Postrza≥ w gnieünieÒskiej potrzebie", "Po≥oniny niebieskie",
			"Poøegnalny ton", "Poøegnanie", "Preludium dla Leonarda", "Prosto za parowem",
			"Przechy≥y", "Przejúcie PolakÛw przez Morze Czerwone", "Psalm rodowodowy", "Quasimodo",
			"Raskolnikow", "Rozbite oddzia≥y", "Rozmyúlania nad wodospadem", "Rudy goúÊ",
			"Samantha", "Sanctus", "Scarlett", "Sen Katarzyny II", "Skrzetuski Wielkopolanin",
			"Stara Maui", "Strπcanie anio≥Ûw", "Stworzenie úwiata", "Szanta dziewicy", "SzczÍúcie",
			"Szkuner I'm Alone", "Szwoleøerowie", "Teodycea", "Testament mÛj",
			"Tomasz i Albert ñ historyjka hagiograficzna", "Tradycja", "Tysiπce mil",
			"Walka Jakuba z anio≥em", "Wed≥ug Gombrowicza - narodu obraøanie",
			"Wojtka Bellona ostatnia ziemska podrÛø do W≥odawy", "WrÛci wiosna, baronowo",
			"WypiÊ wypijemy", "W≥odzimierz Iljicz Lenin",
			"Z XVI-wiecznym portretem trumiennym rozmowa", "Zabawa podmiejska",
			"Zaparcie siÍ aposto≥a Piotra", "ZapiszÍ úniegiem w kominie",
			"Zbieg okolicznoúci ≥agodzπcych", "Zbroja", "Zegarmistrz úwiat≥a", "Zemsta",
			"Zmartwychwstanie Mandelsztama", "Zwπtpienie", "Z≥oto dla zuchwa≥ych", "åmiech",
			"èrÛd≥o" };
}
